import type { LevelBlueprint } from '../types.ts';

/**
 * MODALITÀ ASSEDIO — la marea avanza di un passo dopo ogni pedina posata.
 * È l'unica modalità in cui l'ordine delle mosse conta: le pedine diventano
 * dighe, e non giocare è a sua volta una mossa.
 */
export const ASSEDIO_LEVELS: readonly LevelBlueprint[] = [
  {
    id: 'a01',
    mode: 'assedio',
    name: 'La marea',
    lesson: 'La marea avanza di una casella dopo ogni pedina che posi. Le tue pedine la fermano: sono dighe.',
    hint: 'La stanza ha un solo ingresso, e la marea ci arriva in cinque mosse. Tappalo subito: l’interno cadrà da solo.',
    grid: [
      '* . . # # # #',
      '. . . # 6 6 #',
      '. . . . 6 6 #',
      '. . . # 6 6 #',
      '. 2 . # # # #',
      '. . 2 . . . .',
    ],
    stones: 4,
    objective: { kind: 'maximize', medals: { bronze: 20, silver: 30, gold: 40 } },
  },
  {
    id: 'a02',
    mode: 'assedio',
    name: 'Due argini',
    lesson: 'La sorgente è a due passi dal corridoio: qui non conta cosa giochi, conta quando.',
    hint: 'Il corridoio centrale alimenta entrambe le stanze. Due pedine nel punto giusto le salvano tutte e due — ma se perdi anche solo due mosse, è finita.',
    grid: [
      '. . . . * . . . .',
      '. # # # . # # # .',
      '. # 8 8 . 8 8 # .',
      '. # 8 8 . 8 8 # .',
      '. # # # . # # # .',
      '. 3 . . . . . 3 .',
    ],
    stones: 4,
    objective: { kind: 'maximize', medals: { bronze: 32, silver: 50, gold: 70 } },
  },
  {
    id: 'a03',
    mode: 'assedio',
    name: 'Fermarsi in tempo',
    lesson: 'La macchia blocca l’accerchiamento come una roccia: può sigillare il varco al posto tuo. Ma avanza di un passo per ogni pedina, quindi smettere di giocare è a sua volta una mossa.',
    hint: 'Non ti servono tre pedine per tappare il varco largo tre: lascia che sia la marea a chiuderlo. Una sola pedina dentro la stanza le impedisce di entrare — poi fermati, prima che faccia il passo di troppo.',
    grid: [
      '# # # # # # # # #',
      '# 9 9 9 9 9 9 9 #',
      '# 9 9 9 9 9 9 9 #',
      '# # . . . # # # #',
      '4 . . . . . . . 4',
      '. . . * . . . . .',
    ],
    stones: 5,
    objective: { kind: 'maximize', medals: { bronze: 60, silver: 100, gold: 134 } },
  },
  {
    id: 'a04',
    mode: 'assedio',
    name: 'Tenaglia',
    lesson: 'La macchia blocca l’accerchiamento esattamente come una roccia: puoi appoggiarle contro il tuo perimetro.',
    hint: 'Non difendere tutto. Guarda quale tesoro la marea raggiunge per ultimo e costruisci lì.',
    grid: [
      '* . . . . . . . *',
      '. . . . . . . . .',
      '. . 9 9 . 4 4 . .',
      '. . 9 9 . 4 4 . .',
      '. . . . . . . . .',
      '. . 4 4 . 9 9 . .',
      '. . . . . . . . .',
    ],
    stones: 6,
    objective: { kind: 'maximize', medals: { bronze: 24, silver: 40, gold: 54 } },
  },
  {
    id: 'a05',
    mode: 'assedio',
    name: 'La corsa',
    lesson: 'Le caselle più vicine alla sorgente sono quelle che perderai per prime: l’ordine di raccolta è il vero problema.',
    hint: 'Il valore cresce allontanandosi dalla marea. Ma ciò che è lontano può aspettare: prendi prima ciò che sta per essere inghiottito.',
    grid: [
      '* . . . . . . . .',
      '. . . . . . . . .',
      '. 3 . 5 . 7 . 9 .',
      '. . . . . . . . .',
      '. 3 . 5 . 7 . 9 .',
      '. . . . . . . . .',
      '. . . . . . . . .',
    ],
    stones: 7,
    objective: { kind: 'maximize', medals: { bronze: 20, silver: 33, gold: 45 } },
  },
  {
    id: 'a06',
    mode: 'assedio',
    name: 'L’ultima diga',
    lesson: 'Marea e moltiplicatori nello stesso quadro: due pedine di sola difesa possono valere più di quattro di raccolta.',
    hint: 'La sorgente è proprio sotto il varco della cittadella: hai due mosse, non una di più. Ciò che sta in basso a sinistra è già perduto.',
    grid: [
      '. . . . . . . . . . .',
      '. . . . . . . . . . .',
      '. . # # # # # . . . .',
      '. . # 5 5 5 # . . . .',
      '. . # 5 .x3 5 # . . . .',
      '. . # 5 5 5 # . . . .',
      '. . # . . # # . . . .',
      '. . . . . . . . . . .',
      '. . 6 . * . 6 . 6 . .',
    ],
    stones: 6,
    objective: { kind: 'maximize', medals: { bronze: 60, silver: 110, gold: 150 } },
  },
];
