import type { LevelBlueprint } from '../types.ts';

/**
 * MODALITÀ DOMINIO — massimizzare il punteggio conquistando e accerchiando.
 * È il capitolo che insegna la grammatica di base: perimetro, cattura,
 * territori connessi, moltiplicatori, segno.
 */
export const DOMINIO_LEVELS: readonly LevelBlueprint[] = [
  {
    id: 'd01',
    mode: 'dominio',
    name: 'Il primo recinto',
    lesson: 'Una regione vuota completamente circondata dalle tue pedine viene catturata: la ottieni senza spendere nulla.',
    hint: 'Ti servirebbero 9 pedine per prendere tutto il centro. Ne hai 8. Lascia che sia l’accerchiamento a regalarti la nona casella.',
    grid: [
      '. . . . .',
      '. 1 2 1 .',
      '. 2 5 2 .',
      '. 1 2 1 .',
      '. . . . .',
    ],
    stones: 8,
    objective: {
      kind: 'maximize',
      medals: { bronze: 9, silver: 13, gold: 17 },
    },
  },
  {
    id: 'd02',
    mode: 'dominio',
    name: 'Muri di pietra',
    lesson: 'Le rocce sono muri gratuiti: chiudono il perimetro al posto tuo. Un solo varco, una sola pedina.',
    hint: 'La fortezza ha un’unica apertura in basso. Tappala.',
    grid: [
      '2 . . . . . 2',
      '. # # # # # .',
      '. # 4 4 4 # .',
      '. # 4 4 4 # .',
      '. # 4 4 4 # .',
      '. # # . # # .',
      '2 . . . . . 2',
    ],
    stones: 4,
    objective: {
      kind: 'maximize',
      medals: { bronze: 30, silver: 38, gold: 42 },
    },
  },
  {
    id: 'd03',
    mode: 'dominio',
    name: 'Camera sigillata',
    lesson: 'Una sacca chiusa dalle sole rocce non vale nulla: la cattura scatta solo se la regione confina con una tua pedina.',
    hint: 'Devi entrare nella stanza. Sfonda su una casella che vale 0: le altre sette cadranno da sole.',
    grid: [
      '. . 1 . . 1 . .',
      '. # # # # # # .',
      '. # 2 2 . 5 # .',
      '. # 2 2 . 5 # .',
      '. # # # # # # .',
      '. . 1 . . 1 . .',
    ],
    stones: 3,
    objective: {
      kind: 'maximize',
      medals: { bronze: 18, silver: 19, gold: 20 },
    },
  },
  {
    id: 'd04',
    mode: 'dominio',
    name: 'Terra avvelenata',
    lesson: 'La cattura è automatica e non si può rifiutare: chiudere un’area piena di caselle negative è un autogol.',
    hint: 'Non chiudere mai il cerchio: cattureresti tutto il veleno. Ma nota che l’8 centrale, preso da solo, è un territorio a sé.',
    grid: [
      '. . . . . . .',
      '. 3 3 3 3 3 .',
      '. 3 -9 -9 -9 3 .',
      '. 3 -9 8 -9 3 .',
      '. 3 -9 -9 -9 3 .',
      '. 3 3 3 3 3 .',
      '. . . . . . .',
    ],
    stones: 6,
    objective: {
      kind: 'maximize',
      medals: { bronze: 12, silver: 18, gold: 23 },
    },
  },
  {
    id: 'd05',
    mode: 'dominio',
    name: 'Due recinti',
    lesson: 'I territori non connessi si sommano: puoi coltivare più aree separate nella stessa partita.',
    hint: 'Prendi tutto il blocco di sinistra, poi isola il 9 di destra senza toccare i suoi vicini.',
    grid: [
      '. . . . . . . . .',
      '. . . . . . . . .',
      '. . 7 7 . -6 -6 . .',
      '. . 7 7 . -6 9 . .',
      '. . 7 7 . -6 -6 . .',
      '. . . . . . . . .',
      '. . . . . . . . .',
    ],
    stones: 9,
    objective: {
      kind: 'maximize',
      medals: { bronze: 35, silver: 45, gold: 51 },
    },
  },
  {
    id: 'd06',
    mode: 'dominio',
    name: 'Il labirinto',
    lesson: 'Prima di sfondare una stanza, fai la somma di ciò che contiene. Non tutte le porte vanno aperte.',
    hint: 'Una delle due camere è in perdita. Lasciala chiusa e raccogli il resto.',
    grid: [
      '. . . . . . . . .',
      '. # # # # # # # .',
      '. # 8 8 # 3 3 # .',
      '. # 8 -30 # 3 3 # .',
      '. # # # # # # # .',
      '. . 2 . . . 2 . .',
      '. . . . . . . . .',
    ],
    stones: 5,
    objective: {
      kind: 'maximize',
      medals: { bronze: 10, silver: 14, gold: 16 },
    },
  },
  {
    id: 'd07',
    mode: 'dominio',
    name: 'Moltiplicatori',
    lesson: 'Un moltiplicatore agisce su tutto il territorio connesso che lo contiene, non sulla singola casella.',
    hint: 'Costruisci un ponte fino alla casella ×3: il moltiplicatore triplicherà l’intera somma del gruppo.',
    grid: [
      '. . . . . . .',
      '. 5 5 5 5 5 .',
      '. . . . . . .',
      '. . . 5x3 . . .',
      '. . . . . . .',
      '. . . . . . .',
      '. . . . . . .',
    ],
    stones: 6,
    objective: {
      kind: 'maximize',
      medals: { bronze: 40, silver: 60, gold: 75 },
    },
  },
  {
    id: 'd08',
    mode: 'dominio',
    name: 'Il cuore moltiplicato',
    lesson: 'Accerchiare un moltiplicatore costa pochissimo e vale moltissimo: il perimetro entra nel gruppo.',
    hint: 'Chiudi il ×4 con le quattro caselle ortogonali, poi ingrassa il gruppo con gli angoli. Il -10 resta fuori.',
    grid: [
      '. . . . . . . .',
      '. 6 6 6 . . . .',
      '. 6 .x4 6 -10 . . .',
      '. 6 6 6 . . . .',
      '. . . . . . . .',
      '. . . . 9 9 . .',
      '. . . . 9 9 . .',
    ],
    stones: 8,
    objective: {
      kind: 'maximize',
      medals: { bronze: 96, silver: 150, gold: 192 },
    },
  },
  {
    id: 'd09',
    mode: 'dominio',
    name: 'La trappola',
    lesson: 'Segno per moltiplicatore: una base negativa moltiplicata diventa una voragine. ×5 su -32 fa -160.',
    hint: 'Il ×5 al centro è un’esca. Ignoralo e raccogli i 7.',
    grid: [
      '. . . . . . .',
      '. -8 -8 -8 . . .',
      '. -8 .x5 -8 . 7 .',
      '. -8 -8 -8 . 7 .',
      '. . . . . . .',
      '. . 7 7 7 . .',
      '. . . . . . .',
    ],
    stones: 6,
    objective: {
      kind: 'maximize',
      medals: { bronze: 20, silver: 28, gold: 35 },
    },
  },
  {
    id: 'd10',
    mode: 'dominio',
    name: 'Composizione',
    lesson: 'Più moltiplicatori nello stesso territorio si compongono per prodotto: ×2 e ×2 fanno ×4.',
    hint: 'Un’unica catena che tocca entrambi i ×2. E resta lontano dai -12.',
    grid: [
      '. . . . . . .',
      '. 5 5 5 5 5 .',
      '. .x2 . . . .x2 .',
      '. . . . . . .',
      '. -12 . . . -12 .',
      '. . . . . . .',
      '. . . . . . .',
    ],
    stones: 8,
    objective: {
      kind: 'maximize',
      medals: { bronze: 50, silver: 80, gold: 100 },
    },
  },
  {
    id: 'd11',
    mode: 'dominio',
    name: 'Il grande assedio',
    lesson: 'Il costo di un accerchiamento è il perimetro, non l’area: tre pedine possono valere trentotto caselle.',
    hint: 'La fortezza ha un varco largo tre. Chiudilo e incassa tutto l’interno, moltiplicatore compreso.',
    grid: [
      '. . . . . . . . . . .',
      '. # # # # # # # # # .',
      '. # 3 3 3 3 3 3 3 # .',
      '. # 3 . . . . . 3 # .',
      '. # 3 . 6x2 . 6 . 3 # .',
      '. # 3 . . . . . 3 # .',
      '. # 3 3 3 3 3 3 3 # .',
      '. # # # . . . # # # .',
      '. . 4 . . . . . 4 . .',
    ],
    stones: 6,
    objective: {
      kind: 'maximize',
      medals: { bronze: 90, silver: 144, gold: 156 },
    },
  },
  {
    id: 'd12',
    mode: 'dominio',
    name: 'Egemonia',
    lesson: 'Tutto insieme. A volte conviene assorbire una perdita per unire due moltiplicatori: ×3 e ×4 diventano ×12.',
    hint: 'La cittadella ×3 e il ×4 isolato valgono molto da soli. Ma se un ponte li unisse in un solo territorio, i moltiplicatori si comporrebbero: vale la pena pagare un -15?',
    grid: [
      '. . . . . . . . . . .',
      '. 4 4 4 4 . . . . . .',
      '. 4 # # 4 . -15 -15 . . .',
      '. 4 # .x3 4 . -15 8x4 -15 . .',
      '. 4 4 4 4 . -15 -15 . . .',
      '. . . . . . . . . . .',
      '. . 2 2 2 . # # # . .',
      '. . 2 2 2 . # 9 9 # .',
      '. . 2 2 2 . # 9 9 # .',
      '. . . . . . # # . # .',
      '. . . . . . . . . . .',
    ],
    stones: 14,
    objective: {
      kind: 'maximize',
      medals: { bronze: 180, silver: 320, gold: 492 },
    },
  },
];
